name: app_rap_fr
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - pandas=1.3.5=py38h5d928e2_0
  - plotly=5.4.0=pyhd8ed1ab_0
  - pymongo=3.11.0=py38ha925a31_0
  - streamlit=1.3.0=pyhd8ed1ab_0